version: '3.1'
services:
  postgres:
    image: postgres:13.2
    container_name: postgres-kist
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql-lc/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - ball
networks:
  ball:
    driver: "bridge"
volumes:
  pgdata:
    driver: local
