server:
  port: 8099
spring:
  data:
    cassandra:
      keyspace-name: ${ASTRA_DB_KEYSPACE}
      username: ${ASTRA_DB_USERNAME}
      password: ${ASTRA_DB_PASSWORD}
      # Increase timeouts when connecting to Astra from a dev workstation
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

datastax.astra:
  secure-connect-bundle: ${ASTRA_DB_BUNDLE}
app:
  retry:
    maxAttempts: 5
